### ISSUE TITLE
Total number of training examples

### ISSUE THREAD

**Issue by conceptofmind** [facebookresearch/Shepherd#12]
Hi,

Thank you for your great research.

I was wondering how many examples were used in total to train the model? I see ~1300 examples provided in the data folder.

Thank you,

Enrico

**Comment by PingYu-iris** [comment]
We utilized approximately 8,000 training data points for our project. Out of these, 1,300 were sourced from human annotators, while the remainder were obtained from community platforms including Reddit and Stack Exchange. Due to legal constraints, we are unable to share the community-sourced data at the moment.

**Comment by conceptofmind** [comment]
> We utilized approximately 8,000 training data points for our project. Out of these, 1,300 were sourced from human annotators, while the remainder were obtained from community platforms including Reddit and Stack Exchange. Due to legal constraints, we are unable to share the community-sourced data at the moment.

Hi PingYu,

Thank you for the update.

Are there any available scripts that we can run to reproduce the data obtained from the community platforms? In this instance, you would not have to provide the data and we could generate it ourselves if there are legal concerns.

Thank you,

Enrico
